---
# Source: ai-starter-kit/charts/mlflow/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-starter-kit-mlflow
  labels:
    helm.sh/chart: mlflow-0.12.0
    app: mlflow
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: ai-starter-kit
    version: "2.19.0"
    app.kubernetes.io/version: "2.19.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
