---
# Source: ai-starter-kit/charts/jupyterhub/templates/image-puller/serviceaccount-continuous.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-starter-kit-jupyterhub-continuous-image-puller
  labels:
    component: image-puller
    app.kubernetes.io/component: image-puller
    app: "jupyterhub"
    release: "ai-starter-kit"
    chart: jupyterhub-4.2.0
    heritage: Helm
    app.kubernetes.io/name: "jupyterhub"
    app.kubernetes.io/instance: "ai-starter-kit"
    helm.sh/chart: jupyterhub-4.2.0
    app.kubernetes.io/managed-by: Helm
  annotations:
