---
# Source: ai-starter-kit/templates/local-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-starter-kit-models-cache-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/models-cache"
